### ISSUE TITLE
Error: Unable to access jarfile Pokemate.jar

### ISSUE THREAD

**Issue by lifeofbolo** [SwipeX/PokeMate#220] opened 2016-07-30 13:14 UTC
What did i do wrong?

**Comment by veskoz** [comment] 2016-07-30 13:45
Can u descrive just alittle bit what u did ?

**Comment by lifeofbolo** [comment] 2016-07-30 13:54
im trying to run it on mac. is it even compatible with mac?
im new to this, so i just followed the usage pretty roughly
<img width="568" alt="skaermbillede 2016-07-30 kl 15 53 25" src="https://cloud.githubusercontent.com/assets/20727032/17270895/ca811052-566d-11e6-819d-143a215db06e.png">

**Comment by SippieCup** [comment] 2016-07-30 13:57
This is a file permissions issue, copy and paste it to another location and see if it works, or edit the permissions manually to be +rwx for all users.

**Comment by lifeofbolo** [comment] 2016-07-30 14:00
i installed the Java SDK. Is it the right one?

**Comment by veskoz** [comment] 2016-07-30 14:04
Java runs everywhere as long as you have a VM.
Imo u don't have permissions to run the jar.
Unfortunally i don't know anything about Mac

**Comment by lifeofbolo** [comment] 2016-07-30 14:35
@SippieCup do i have to compile the master?

**Comment by SippieCup** [comment] 2016-07-30 14:40
I would also suggest downloading the [latest release of PokeMate](https://github.com/SwipeX/PokeMate/releases/tag/0.3.0), it is up to date with the last commit.

Once you download it, open up terminal, navigate to the location of the jar, and use the following command:

`sudo chmod 777 Pokemate-0.3.0.jar`

then try running it

`java -jar Pokemate-0.3.0.jar`

It should work then

**Comment by lifeofbolo** [comment] 2016-07-30 14:49
should i only download the jar file or the source?

**Comment by SippieCup** [comment] 2016-07-30 14:49
the jar is fine.

**Comment by lifeofbolo** [comment] 2016-07-30 15:00
still bump
<img width="687" alt="skaermbillede 2016-07-30 kl 16 59 33" src="https://cloud.githubusercontent.com/assets/20727032/17271242/090015c2-5677-11e6-8d04-1de2fe01c4be.png">

**Comment by lifeofbolo** [comment] 2016-07-30 15:04
tried opening terminal in the folder
<img width="567" alt="skaermbillede 2016-07-30 kl 17 02 23" src="https://cloud.githubusercontent.com/assets/20727032/17271280/6dae1f0a-5677-11e6-92f8-f9ccb04df818.png">

**Comment by SippieCup** [comment] 2016-07-30 15:05
Its working now - you just need to configure the config file for it now. Please visit the wiki on how to do that.

**Comment by lifeofbolo** [comment] 2016-07-30 15:21
@SippieCup i did the config file but its still giving me this...
<img width="774" alt="skaermbillede 2016-07-30 kl 17 19 29" src="https://cloud.githubusercontent.com/assets/20727032/17271371/085bfb10-567a-11e6-9ae7-a7a0ffc706ac.png">

**Comment by SippieCup** [comment] 2016-07-30 15:23
please ensure that the file is named just "config.properties" and does not have a hidden extension.

alternatively, in the terminal type the following, where [tab] represents the you pressing the tab button:

`mv config.prop**[TAB]** config.properties`

it will work after that.

**Comment by kylestev** [comment] 2016-07-30 15:30
gotta love the nuances of OS X/macOS

**Comment by lifeofbolo** [comment] 2016-07-30 15:31
@SippieCup its running. copied the api and inserted it in tha java. but i didn't get the user interface or anything just the terminal running all the data

**Comment by kylestev** [comment] 2016-07-30 15:31
you have to enable the ui in the configuration

**Comment by SippieCup** [comment] 2016-07-30 15:31
Change `show=false` to `show=true` in the config

**Comment by lifeofbolo** [comment] 2016-07-30 15:39
@SippieCup hmm.. the map doesn't seem to be working. looks like im in the middle of the sea.

**Comment by SippieCup** [comment] 2016-07-30 15:51
That would be your location being wrong, not the map :)

**Comment by lifeofbolo** [comment] 2016-07-30 16:05
@SippieCup 
<img width="811" alt="skaermbillede 2016-07-30 kl 18 04 37" src="https://cloud.githubusercontent.com/assets/20727032/17271588/205f6322-5680-11e6-864e-90609687d51f.png">
<img width="608" alt="skaermbillede 2016-07-30 kl 18 05 23" src="https://cloud.githubusercontent.com/assets/20727032/17271595/3b8f2f74-5680-11e6-8f9f-b54eb129353c.png">

**Comment by SippieCup** [comment] 2016-07-30 16:23
That is the default location when something cannot be found on the google maps query. It is because you defined location_by_name, which overrides the latitude and longitude values.

add a "#" to the front of  `location_by_name` to make it `#location_by_Name` so it is commented out and you will be in Denmark again.

**Comment by SippieCup** [comment] 2016-07-30 16:24
Also, I highly suggest against using the location_by_name functionality until it is more developed.

Edit: Accidently closed, reopening until issue is solved.

**Comment by lifeofbolo** [comment] 2016-07-30 16:29
@SippieCup Should i go with coordinates only then? if so, what should i type in the location_name?

**Comment by lifeofbolo** [comment] 2016-07-30 16:38
@SippieCup what does it mean?
<img width="779" alt="skaermbillede 2016-07-30 kl 18 37 21" src="https://cloud.githubusercontent.com/assets/20727032/17271746/b4ce7062-5684-11e6-81e0-2f534f95021a.png">

**Comment by SippieCup** [comment] 2016-07-30 16:39
Thats working as intended,  those are requests done to build the path your bot will walk.

**Comment by lifeofbolo** [comment] 2016-07-30 16:49
@SippieCup  Cool! Thank you very much! :-D

**Comment by lifeofbolo** [comment] 2016-07-30 18:43
@SippieCup Why am i not getting anything? like XP/hour after 1 hour and 25 minutes?
<img width="1178" alt="skaermbillede 2016-07-30 kl 20 36 20" src="https://cloud.githubusercontent.com/assets/20727032/17272431/314ee25a-5696-11e6-91aa-46e8ca60467f.png">

**Comment by SippieCup** [comment] 2016-07-30 18:45
We discovered a bug that happens when you are softbanned, I'll be updating the binary soon once the another bug is ironed out. If you want it now, you will have to build from source.

**Closed as completed by SippieCup** 2016-07-30 18:45 UTC
