### ISSUE TITLE
com.pokegoapi.exceptions.LoginFailedException

### ISSUE THREAD

**Issue by Simpuhl** [SwipeX/PokeMate#14] opened 2016-07-24 05:52 UTC
https://i.imgur.com/QLRf1v1.png

Got this but then it just continued working

Any idea?

**Comment by SonnyX** [comment] 2016-07-24 10:27
@SwipeX I've got a fix for most Google Auth related problems on my fork. 
The fix was made in PokeMate.java and the build.gradle: 
https://github.com/SonnyX/PokeMate/blob/master/src/main/java/dekk/pw/pokemate/PokeMate.java
https://github.com/SonnyX/PokeMate/blob/master/build.gradle
Copy pasting these two files into your project should do it. (Didn't do a Pull request since I would reformat your entire project)

Edit: I just ran into an Login Error due to an expired key...

```
Exception in thread "main" com.pokegoapi.exceptions.LoginFailedException: Error  in API Url 
    at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:149)
    at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:79)
    at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:67)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:66)
    at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:59)
    at dekk.pw.pokemate.PokeMate.main(PokeMate.java:72)
```

**Comment by SwipeX** [comment] 2016-07-24 13:39
@SonnyX Ive merged a bit of you token writing into next PR

**Comment by SwipeX** [comment] 2016-07-24 14:03
Let me know on 1.5 release

**Comment by Simpuhl** [comment] 2016-07-24 14:40
Can't even run now

https://i.imgur.com/TxZRLZ8.png

**Comment by null-dev** [comment] 2016-07-24 20:54
This happens for me when I open the app and then try opening PokeMate. Usually I just delete 'token.txt' after I open the app or when I see this error.

As of commit 3fa1261625c82e12dc8e90002d1ce189716b1313, tokens are disabled entirely however. Tokens have never caused problems for me so I would like to see them re-enabled.

**Comment by SwipeX** [comment] 2016-07-24 22:42
@null-dev the problem is that they expire. And need to be renewed

**Comment by BurakDev** [comment] 2016-07-24 23:10
You just need check token expiration and renew it when needed, don't disable it entirely maybe can cause a spam detection.

**Comment by SwipeX** [comment] 2016-07-25 03:26
Renewing will be added when I can find a good solution, as for now google will need to reauthenticate manually.

**Comment by SonnyX** [comment] 2016-07-25 10:47
@SwipeX Once an a getter method for Refresh_token is available it will become rather easy to reauthenticate automatically, once it becomes available I will update my git.

**Comment by SippieCup** [comment] 2016-07-30 10:08
This has been fixed, closing thread.

**Closed as completed by SippieCup** 2016-07-30 10:08 UTC
