### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by Zerotask** [SwipeX/PokeMate#180] opened 2016-07-28 16:48 UTC
There is no PokeMate.jar. There is only a PokeMate.java in the folder PokeMate-electron\src\main\java\dekk\pw\pokemate. I tried to compile it: javac PokeMate.java and got 44 errors. I'm using JDK 8 Update 101 (newest) 32 bit.

**Comment by BurakDev** [comment] 2016-07-28 17:00
Jar releases are here : https://github.com/SwipeX/PokeMate/releases

And if you want build it from source you need gradle.

**Comment by soccertj** [comment] 2016-07-28 17:12
I got this error http://imgur.com/a/6oHCE

**Comment by veskoz** [comment] 2016-07-28 17:19
Seems like an issue: https://github.com/SwipeX/PokeMate/issues/172

**Comment by Zerotask** [comment] 2016-07-28 17:36
Thanks Burak for the fast reply. I tried ptc but it seems to be down, then I tried it with a google account and got the following error:

![image](https://cloud.githubusercontent.com/assets/20150243/17222889/940d5d6a-54fa-11e6-874d-6fafd3eb182c.png)

**Comment by kylestev** [comment] 2016-07-28 17:36
> PokeMate-electron

You should not be using the electron branch. Use the `master` (default) branch if you want to build from source. If you want to build from source, you will need gradle as others have mentioned.

**Comment by kylestev** [comment] 2016-07-28 17:37
> Thanks Burak for the fast reply. I tried ptc but it seems to be down, then I tried it with a google account and got the following error:

This is indeed a duplicate of #112 then.

**Closed as completed by kylestev** 2016-07-28 17:37 UTC
Labels: duplicate
