### ISSUE TITLE
Transfer Pokemon

### ISSUE THREAD

**Issue by Simpuhl** [SwipeX/PokeMate#9] opened 2016-07-24 00:14 UTC
Is it possible to make it so it always keeps at least 1 type of each Pokemon and only transfers the lowest one?

I signed in and it literally transferred like 50 Pokemon right off the back including some HIGH CP ones that were 1k+ just because they were doubles 

Also save candy if you don't own the 3rd evolve etc?

**Comment by SwipeX** [comment] 2016-07-24 03:09
Currently it keeps the highest CP of any pokemon. Yes if your second is a 1k+ CP it will also be transferred.

I plan on adding a setting to allow only the 'cheap' evoultions as it is better exp

**Comment by Simpuhl** [comment] 2016-07-24 03:18
That's not entirely true because it transferred like 50 of mine when I first launched it. Not leaving a single 1 of a specific type in some cases. An example I had 3 Squirtle, and it transferred all 3. It should keep the highest one. Always keep at-least 1 and the highest one.

Also, maybe we can somehow keep all Pokemon with really high stats instead of transfer? 

Lastly, if we don't own all 3 evolution of a specific type maybe it will save the candy instead of auto evolve?

**Comment by SwipeX** [comment] 2016-07-24 03:20
I still have to add the settings for it to be customizable. but currently it keeps pokemon with an IV > 90%. There will be more settings to come soon.

It does keep the best type of a pokemon I can assure you. It is possible that it did evolve it.

The feature will be released in the next release.

**Comment by Simpuhl** [comment] 2016-07-24 03:21
When did you add that feature? Currently I'm using Release 2, which I don't think its doing that

**Comment by Simpuhl** [comment] 2016-07-24 03:22
Also can you change the txt from "lvl" to "CP" maybe? haha

**Comment by Simpuhl** [comment] 2016-07-24 03:51
I had over 200 pokeballs and then I started failing to catch, i logged in and no pokeballs left. Did it drop them? 

It only cought about 20ish pokemon before they all started to flee

**Comment by paradoxism13** [comment] 2016-07-24 12:31
I left the settings on the default 90% IV... and it transferred a 15/14/15 eevee after it caught it.

Edit:
Not the Eevee, but this is still a 95% IV pokemon
http://imgur.com/a/MZUOr

**Comment by pkgofan** [comment] 2016-07-24 15:04
> Currently it keeps the highest CP of any pokemon. Yes if your second is a 1k+ CP it will also be transferred.

Are you sure?  I just tried this and it did the following even though I only have 1 of each.
Transferring 1/1 FLAREON CP 999 [6/6/6]
Transferring 1/1 HAUNTER CP 539 [9/13/9]
Transferring 1/1 VULPIX CP 377 [5/6/5]
Transferring 1/1 JIGGLYPUFF CP 471 [12/12/12]
Transferring 1/1 VAPOREON CP 1043 [13/2/13]

Also it seems to be transferring pokemon > 90% IP

Transferring 15/32 DRATINI CP 201 [13/15/13]
Transferring 1/1 ELECTABUZZ CP 1199 [15/15/15]
Transferring 4/4 GROWLITHE CP 714 [14/14/14]
Transferring 3/4 CATERPIE CP 225 [15/15/15]

**Comment by paradoxism13** [comment] 2016-07-24 18:23
Same here.

http://imgur.com/a/2clXZ

**Comment by Simpuhl** [comment] 2016-07-24 18:26
OUCH

**Comment by paradoxism13** [comment] 2016-07-24 18:59
She was perfect... She was divine. And then Professor Willow stuffed her with all the rejects into the grinder. Like all the others, she became candy. :(

**Comment by pkgofan** [comment] 2016-07-24 19:05
I couldn't reproduce after pulling in the latest code, but then again I've also starred the pokemon I want to keep and have none of the big ones left after running it earlier today.

**Comment by paradoxism13** [comment] 2016-07-24 20:20
I tried

#What IV% to keep pokemon at
iv-ratio=99

So only 100% 15/15/15 perfect IV pokemon with higher CP can replace perfect IV pokemon.

It transferred a 15/15/15 pokemon again. What it kept was just a random non-perfect IV pokemon with just a tad bit higher CP.

**Comment by pkgofan** [comment] 2016-07-24 20:33
Think I found the problem.  The math is legit but the logging statement is printing [stamina, defense, stamina] and not [attack, defense, stamina] hence it looks like it's trashing valuable pokemon.

`System.out.println("Transferring " + (list.indexOf(p) + 1) + "/" + list.size() + " " + p.getPokemonId() + " CP " + p.getCp() + " [" + p.getIndividualStamina() + "/" + p.getIndividualDefense() + "/" + p.getIndividualStamina() + "]");
`

**Comment by paradoxism13** [comment] 2016-07-24 22:47
Nice catch. I now feel better. Those perfects crushed and melted into candy were not so perfect after all.

**Comment by SwipeX** [comment] 2016-07-25 03:24
@pkgofan  nice catch!

**Comment by SwipeX** [comment] 2016-07-25 03:25
anyone have issues with me closing this or does it need any more fixing?

**Comment by pkgofan** [comment] 2016-07-26 17:58
One related question.  I hatched some eggs, ran this tool from today's source and then saw the following

Transferring 1/2 LAPRAS CP 650 [11/11/14]
Transferring 1/2 PORYGON CP 323 [14/10/15]

It saved a CP 1134 [15/2/6] Lapras and a CP 542 [15/7/3] Porygon.  Is the logic to transfer based on a combination of current CP and IV?  I had assumed it would try for the best IV. Thanks.

**Comment by Simpuhl** [comment] 2016-07-26 18:00
It seems to work fine for me.

I have chosen to keep everything over 1000 CP or Anything above 85 IV. It does that.

**Comment by pkgofan** [comment] 2016-07-26 18:03
Oh I get it by default it keeps the highest CP of each pokemon.  Additionally it will keep it if it's above min-cp and iv-ratio.  I was thinking it would compare IV and keep the "better" of the two.  My iv-ratio was set to 90% I'll lower it, thanks.

**Comment by SwipeX** [comment] 2016-07-26 18:10
It just keeps it if it qualifies. You got it now.

**Closed as completed** 2016-07-30 10:07 UTC
Labels: question
