### ISSUE TITLE
[Exception] Contents of buffer are null (InvalidProtocolBufferException)

### ISSUE THREAD

**Issue by kyleshrader** [SwipeX/PokeMate#190] opened 2016-07-28 21:27 UTC
This is happening on startup.

```
Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:114)
    at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:90)
    at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:62)
    at dekk.pw.pokemate.PokeMate.main(PokeMate.java:93)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
    at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:112)
    ... 4 more
```

**Comment by SippieCup** [comment] 2016-07-28 21:29
Server error, we will be handling these errors in an update soon.

**Comment by soccertj** [comment] 2016-07-28 21:35
Mine looks similar but happens while running http://imgur.com/a/fOtZI

**Comment by yirenye** [comment] 2016-07-28 21:49
Same Exception:
Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:114)
    at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:84)
    at com.pokegoapi.api.inventory.Inventories.<init>(Inventories.java:74)
    at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:86)
    at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:62)
    at dekk.pw.pokemate.PokeMate.main(PokeMate.java:93)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
    at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
    at com.pokegoapi.api.inventory.Inventories.updateInventories(Inventories.java:112)
    ... 5 more

**Comment by pkgofan** [comment] 2016-07-28 21:54
Me too, right when I launch

**Comment by AktasC** [comment] 2016-07-28 22:43
Kinda similar error here :

> Exception in thread "main" com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
>   at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:92)
>   at com.pokegoapi.api.player.PlayerProfile.<init>(PlayerProfile.java:74)
>   at com.pokegoapi.api.PokemonGo.<init>(PokemonGo.java:85)
>   at dekk.pw.pokemate.PokeMate.<init>(PokeMate.java:62)
>   at dekk.pw.pokemate.PokeMate.main(PokeMate.java:93)
> Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
>   at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
>   at com.pokegoapi.api.player.PlayerProfile.updateProfile(PlayerProfile.java:90)
>   ... 4 more

**Comment by SSinischo** [comment] 2016-07-28 22:51
Same issue.  Bot is useless since we can't get past it :(

**Comment by jdmloki** [comment] 2016-07-29 00:10
Yeah, I haven't been able to get passed those errors either

**Comment by SippieCup** [comment] 2016-07-29 00:54
I'll be working on this tonight. Please be patient.

**Comment by teyhouse** [comment] 2016-07-29 05:36
It's because of this:
https://www.reddit.com/r/pokemongodev/comments/4v3twy/request_throttling/?st=ir7bgfoo&sh=b47ffeac

**Comment by jinkawasaki333** [comment] 2016-07-29 06:17
I got the same error plus this one:

`com.pokegoapi.exceptions.RemoteServerException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:307)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:270)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:205)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:195)
        at dekk.pw.pokemate.tasks.TagPokestop.run(TagPokestop.java:23)
        at dekk.pw.pokemate.tasks.TaskController.lambda$run$0(TaskController.java:41)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at dekk.pw.pokemate.tasks.TaskController.run(TaskController.java:41)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
        at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:66)
        at com.pokegoapi.api.map.Map.getMapObjects(Map.java:305)
        ... 7 more`

**Comment by SippieCup** [comment] 2016-07-29 06:35
Fixed in my new release. It will be hard to compile from source due to jitpack screwing up.

PR made to SwipeX branch.

https://github.com/SippieCup/PokeMate/releases/tag/2.3.5

**Comment by jinkawasaki333** [comment] 2016-07-29 06:55
@SippieCup Thanks for the fix! Should I just download the full zipped source code, or do I also need to replace "config.properties.template" and "pokemate-all-0.2.3.5.jar"?

**Comment by jinkawasaki333** [comment] 2016-07-29 07:38
@SippieCup The UI and pop-ups cannot be turned off although it has been set in the config :(

**Comment by iDreamInBinary** [comment] 2016-07-29 07:43
@jinkawasaki333 Pretty sure you're using an outdated config file.

Open your config in an editor, press CTRL+H and replace "-" with "_"

**Comment by jinkawasaki333** [comment] 2016-07-29 07:51
@iDreamInBinary Thanks! :D 
The IV percentage is missing in the log in the latest version.
It also doesn't log which pokeball it is using to catch the pokemon. 

It is possible to turn these on?

**Comment by SippieCup** [comment] 2016-07-29 07:52
Its implemented, just not in the config file. Just add it in yourself.

**Comment by gsisso** [comment] 2016-07-29 09:17
@jinkawasaki333  just look for (src/main/java/dekk/pw/pokemate/tasks/CatchPokemon.java) - 
`String output = "Caught a " + StringConverter.convertPokename(target.getPokemonId().name()) + " (" + p.getCp() + " CP)" + " (Candy: " + p.getCandy() + ")";`

and replace with -
`String output = "Caught a " +StringConverter.convertPokename(target.getPokemonId().name()) + " (" + p.getCp() + " CP)" + " Using : "+ pokeball.name() +" (Candy: " + p.getCandy() + ")";`

or something like that.

@SippieCup I have tried to use your sources but seem like issue still there ? does it have something to do with gradle doesn't pull the latest release of pokemon go api ?

**Comment by iDreamInBinary** [comment] 2016-07-29 10:10
That "fix" in pokego api is a bad joke

**Comment by SSinischo** [comment] 2016-07-29 13:59
Let's keep the comments pertinent to the original issue.  With the latest release I am still getting "contents of buffer are null" and can't login.

**Comment by SippieCup** [comment] 2016-07-30 11:25
This has been handled to the best of the ability that the bot can.

Closing thread.

If this becomes an issue again, we may revisit alternative solutions.

**Closed as completed by SippieCup** 2016-07-30 11:25 UTC
