### ISSUE TITLE
JavaFX Application Thread exception

### ISSUE THREAD

**Issue by techinaflash** [SwipeX/PokeMate#60] opened 2016-07-26 01:25 UTC
I get the following exception thread.  App is still working, but I don't think this exception should be happening

Profile update : 540595 XP on LVL 23 84.48 % to LVL 24 - Gained 980 XP - XP/H: 22431 - Runtime: 00:02:37
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at com.pokegoapi.api.inventory.CandyJar.getCandies(CandyJar.java:80)
        at com.pokegoapi.api.pokemon.Pokemon.getCandy(Pokemon.java:150)
        at dekk.pw.pokemate.PokeMateUI.lambda$null$5(PokeMateUI.java:162)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(Unknown Source)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at com.pokegoapi.api.inventory.CandyJar.getCandies(CandyJar.java:80)
        at com.pokegoapi.api.pokemon.Pokemon.getCandy(Pokemon.java:150)
        at dekk.pw.pokemate.PokeMateUI.lambda$null$5(PokeMateUI.java:162)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(Unknown Source)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by null-dev** [comment] 2016-07-26 01:58
Duplicate of #50, please close.

**Closed as completed** 2016-07-26 12:12 UTC
Labels: duplicate
